#!/usr/bin/env python3
"""genassets.py — generate AirRadar v7 LVGL image assets (.c, LV_IMG_CF_TRUE_COLOR_ALPHA).

All glyphs are drawn pure white on transparent at 4x supersampling and
downscaled with Lanczos, so LVGL img_recolor can tint them at runtime.
Output: firmware/AirRadar/src/assets/img_*.c
"""
import os
from PIL import Image, ImageDraw

SS = 4  # supersample factor
OUT = os.path.join(os.path.dirname(__file__), "..", "AirRadar", "src", "assets")
os.makedirs(OUT, exist_ok=True)

def canvas(w, h):
    return Image.new("RGBA", (w * SS, h * SS), (0, 0, 0, 0))

def emit(img, name):
    w, h = img.size
    img = img.resize((w // SS, h // SS), Image.LANCZOS)
    w, h = img.size
    px = img.load()
    rows = []
    for y in range(h):
        b = bytearray()
        for x in range(w):
            r, g, bl, a = px[x, y]
            c565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (bl >> 3)
            b += bytes((c565 & 0xFF, c565 >> 8, a))     # lo, hi, alpha
        rows.append(", ".join(f"0x{v:02x}" for v in b))
    body = ",\n  ".join(rows)
    c = f"""/* SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026 Franco Raso. Generated by firmware/tools/genassets.py
 */
// generated by tools/genassets.py — do not edit
#include <lvgl.h>

static const uint8_t {name}_map[] = {{
  {body}
}};

const lv_img_dsc_t {name} = {{
  .header = {{ .cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .always_zero = 0, .reserved = 0,
              .w = {w}, .h = {h} }},
  .data_size = sizeof({name}_map),
  .data = {name}_map,
}};
"""
    with open(os.path.join(OUT, f"{name}.c"), "w") as f:
        f.write(c)
    print(f"{name}: {w}x{h}  {w*h*3} bytes")

def S(v):  # scale helper
    return v * SS

# ---------------- jet (top-down airliner, nose up), 26x26 ----------------
img = canvas(26, 26)
d = ImageDraw.Draw(img)
cx, cy = S(13), S(13)
u = S(26) / 26.0  # 1 design unit
def P(x, y):  # design coords centered
    return (cx + x * u, cy + y * u)
# fuselage (rounded via polygon + ellipse nose)
d.polygon([P(-1.5, -9.5), P(1.5, -9.5), P(1.7, 8.0), P(-1.7, 8.0)], fill="white")
d.ellipse([P(-1.6, -11.6), P(1.6, -8.4)], fill="white")
# main wings (swept)
d.polygon([P(-1.6, -2.4), P(-11.8, 3.6), P(-11.8, 5.4), P(-1.6, 3.4)], fill="white")
d.polygon([P(1.6, -2.4), P(11.8, 3.6), P(11.8, 5.4), P(1.6, 3.4)], fill="white")
# tailplane
d.polygon([P(-1.5, 6.2), P(-5.4, 9.4), P(-5.4, 10.6), P(-1.5, 9.2)], fill="white")
d.polygon([P(1.5, 6.2), P(5.4, 9.4), P(5.4, 10.6), P(1.5, 9.2)], fill="white")
# tail cone
d.polygon([P(-1.7, 8.0), P(1.7, 8.0), P(0.6, 11.2), P(-0.6, 11.2)], fill="white")
emit(img, "img_jet")

# ---------------- glow (radial), 34x34 ----------------
img = canvas(34, 34)
d = ImageDraw.Draw(img)
c = S(17)
for i in range(S(17), 0, -1):
    a = int(150 * (1 - i / S(17)) ** 2)
    d.ellipse([c - i, c - i, c + i, c + i], fill=(255, 255, 255, a))
emit(img, "img_glow")

# ---------------- ISS glyph, 24x14 ----------------
img = canvas(24, 14)
d = ImageDraw.Draw(img)
# solar arrays
d.rounded_rectangle([S(0), S(3), S(8), S(11)], radius=S(1), fill="white")
d.rounded_rectangle([S(16), S(3), S(24), S(11)], radius=S(1), fill="white")
# truss
d.rectangle([S(8), S(6), S(16), S(8)], fill="white")
# body
d.rounded_rectangle([S(9.5), S(3.5), S(14.5), S(10.5)], radius=S(1), fill="white")
emit(img, "img_iss")

# ---------------- route arrowhead, 8x10 ----------------
img = canvas(8, 10)
d = ImageDraw.Draw(img)
d.polygon([(S(0), S(0)), (S(8), S(5)), (S(0), S(10))], fill="white")
emit(img, "img_arrowhead")

# ---------------- weather icons, line style ----------------
# Authored in a 22-unit design space and emitted at WX_PX. The stroke stays at
# a fixed 1.5 px of OUTPUT (LW is in supersampled units and the canvas shrinks
# with it), which is what keeps a line icon legible as it gets smaller — the
# glyph shrinks, the pen does not.
WX_PX = 16                     # must match WX_ICON_PX in ui/ui_cards.cpp
WX_K = WX_PX / 22.0
LW = int(1.7 * SS)             # 6 supersampled -> 1.5 px out

def W(v):                      # 22-unit design coords -> supersampled pixels
    return v * WX_K * SS

def wx_canvas():
    im = canvas(WX_PX, WX_PX)
    return im, ImageDraw.Draw(im)

def cloud(d, dy=0):
    # two lobes + base, stroke style: draw filled then punch inner
    d.arc([W(3), W(7 + dy), W(13), W(17 + dy)], 90, 270, fill="white", width=LW)
    d.arc([W(7), W(4 + dy), W(17), W(14 + dy)], 180, 360, fill="white", width=LW)
    d.arc([W(12), W(7 + dy), W(20), W(15 + dy)], 270, 90, fill="white", width=LW)
    d.line([W(8), W(17 + dy) - LW // 2, W(16), W(17 + dy) - LW // 2],
           fill="white", width=LW)

img, d = wx_canvas()
d.ellipse([W(6.5), W(6.5), W(15.5), W(15.5)], outline="white", width=LW)
import math
for k in range(8):
    a = k * math.pi / 4
    x1 = W(11) + math.cos(a) * W(6.6); y1 = W(11) + math.sin(a) * W(6.6)
    x2 = W(11) + math.cos(a) * W(9.4); y2 = W(11) + math.sin(a) * W(9.4)
    d.line([x1, y1, x2, y2], fill="white", width=LW)
emit(img, "img_wx_sun")

img, d = wx_canvas(); cloud(d, 1); emit(img, "img_wx_cloud")

img, d = wx_canvas(); cloud(d, -1)
for i, x in enumerate([7.5, 11, 14.5]):
    d.line([W(x), W(17), W(x - 1.6), W(21)], fill="white", width=LW)
emit(img, "img_wx_rain")

img, d = wx_canvas(); cloud(d, -1)
for x in [7.5, 11, 14.5]:
    r = W(0.9)
    d.ellipse([W(x) - r, W(19) - r, W(x) + r, W(19) + r], fill="white")
emit(img, "img_wx_snow")

img, d = wx_canvas()
for i, y in enumerate([6, 11, 16]):
    x0 = 3 + (i % 2) * 2
    d.line([W(x0), W(y), W(19 - (i % 2) * 2), W(y)], fill="white", width=LW)
emit(img, "img_wx_fog")

img, d = wx_canvas(); cloud(d, -2)
d.polygon([P2 := None] if False else
          [(W(12), W(13)), (W(8.5), W(18.5)), (W(11), W(18.5)),
           (W(9.5), W(22)), (W(14.5), W(16.5)), (W(11.8), W(16.5))],
          fill="white")
emit(img, "img_wx_storm")

# Wind: three flowing swooshes, each sweeping right and hooking back on
# itself. Earlier attempts used straight lines with small arcs at the ends;
# at 22 px those arcs read as rounded line caps, so the glyph looked like a
# hamburger menu. Curvature along the whole stroke is what makes it read as
# moving air. Drawn from quadratic beziers so the curve stays smooth after
# the 4x supersample downscale.
img, d = wx_canvas()

def _bez(p0, p1, p2, n=44):
    return [((1 - t) ** 2 * p0[0] + 2 * (1 - t) * t * p1[0] + t * t * p2[0],
             (1 - t) ** 2 * p0[1] + 2 * (1 - t) * t * p1[1] + t * t * p2[1])
            for t in [i / n for i in range(n + 1)]]

def _gust(pts):
    d.line([(W(x), W(y)) for x, y in pts], fill="white", width=LW, joint="curve")
    for x, y in (pts[0], pts[-1]):        # round the caps
        r = LW // 2
        d.ellipse([W(x) - r, W(y) - r, W(x) + r, W(y) + r], fill="white")

_gust(_bez((2.5, 7.0), (11.0, 7.0), (14.8, 4.0)) +
      _bez((14.8, 4.0), (18.0, 1.6), (14.2, 2.0))[1:])
_gust(_bez((2.5, 11.6), (12.8, 11.6), (17.0, 8.6)) +
      _bez((17.0, 8.6), (20.4, 6.2), (16.6, 6.4))[1:])
_gust(_bez((2.5, 16.0), (9.0, 16.0), (11.8, 17.9)) +
      _bez((11.8, 17.9), (14.6, 19.9), (11.4, 19.7))[1:])
emit(img, "img_wx_wind")

print("done ->", os.path.abspath(OUT))
